#!/bin/bash

REPO_LIB=repo_lib

. shFlags/src/shflags

# define a 'name' command-line string flag
DEFINE_string 'git' '' 'the git url from github or other website' 'g'

# parse the command-line
FLAGS "$@" || exit 1
eval set -- "${FLAGS_ARGV}"

if [ -z ${FLAGS_git} ]
then
    echo "./sphinx2dash -h for help"
    exit 1
fi

[ -d $REPO_LIB ] || mkdir $REPO_LIB

# Get the project name from git url
name=`echo "${FLAGS_git}" | egrep -o '/[^/]*\.git'`
name=${name#/}
name=${name%.git}
echo "project: $name"

# clone the project
if [ ! -d ${REPO_LIB}/$name ]
then
    git clone --depth 1 ${FLAGS_git} ${REPO_LIB}/$name
fi

cd ${REPO_LIB}/$name/docs

nobaropts=" -D html_theme_options.nosidebar=1"

# add nosidebar to makefile
if ! grep -E -e "$nobaropts" Makefile >/dev/null
then
    sed "s/^SPHINXOPTS *=.*$/&${nobaropts}/" Makefile > Makefile.dash
else
    cp Makefile Makefile.dash
fi

make -f Makefile.dash html
doc2dash -n $name -A _build/html
